INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Umformung', 1, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Stückvergüten', 2, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Anlassen 1', 3, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Schleifen', 4, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Außenfase', 5, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Innenfase', 6, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Warmformgebung', 7, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Fräsen, Drehen, Bohren', 8, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Kaltformgebung', 9, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Anlassen 2', 10, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Reinigungsstrahlen', 11, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'WFG-Nitrieren', 12, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Nitrieren', 13, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Strahlen 0,6mm', 14, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Strahlen 0,4mm', 15, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Strahlen 0,2mm', 16, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Montage', 17, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Farbkennzeichnung', 18, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Warmsetzen', 19, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Kaltsetzen', 20, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Kraftsetzen', 21, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Anlassen 3', 22, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', '100% Sortierung', 23, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Oberflächenbehandlung', 24, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Verpacken', 25, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Sonstiges', 28, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'result', 999, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Umformung', 1, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Stückvergüten', 2, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Anlassen 1', 3, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Schleifen', 4, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Außenfase', 5, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Innenfase', 6, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Warmformgebung', 7, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Fräsen, Drehen, Bohren', 8, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Kaltformgebung', 9, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Anlassen 2', 10, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Reinigungsstrahlen', 11, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'WFG-Nitrieren', 12, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Nitrieren', 13, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Strahlen 0,6mm', 14, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Strahlen 0,4mm', 15, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Strahlen 0,2mm', 16, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Montage', 17, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Farbkennzeichnung', 18, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Warmsetzen', 19, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Kaltsetzen', 20, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Kraftsetzen', 21, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Anlassen 3', 22, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', '100% Sortierung', 23, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Oberflächenbehandlung', 24, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Verpacken', 25, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'Sonstiges', 28, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_prod', 'result', 999, 'prod');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_qs', 'Messmittel', 1, 'qs');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_qs', 'Prüfmaschinen', 2, 'qs');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_qs', 'Technische Lieferbedingungen', 3, 'qs');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_qs', 'Sonstiges', 4, 'qs');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_hsb_qs', 'result', 999, 'qs');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Bürger, André', 0, 'buergera');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Jaire, Christoph', 0, 'jaire');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Kebernik, Thomas', 0, 'kebernikt');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Kleine, Franz-Josef', 0, 'kleine');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Kleineheilmann, Daniel', 0, 'kleineheilmann');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Köster-Pauleikhoff, Daniel', 0, 'pauleikhoff');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Preker, Thomas', 0, 'preker');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_as', 'Russ, Karsten', 0, 'russ');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_prod_name_as', 'Köhler, Daniel', 0, 'koehlerd');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_prod_name_as', 'Mühlentien, Oliver', 0, 'muehlentien');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_qs_name_as', 'Kirchhoff, Jörg', 0, 'krichhoff');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_qs_name_as', 'Köhler, Reinhard', 0, 'koehler');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_ae_name_ifa', 'Ruhose, Jörg', 0, 'ruhose');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_prod_name_ifa', 'Kaemper, Tobias', 0, 'kaemper');
INSERT INTO `t_setup` (`merkmal`, `wert`, `order_no`, `alias`) VALUES ('werteliste_qs_name_ifa', 'Schütz, Sergej', 0, 'schuetz');
